In [27]:
import pandas as pd 
import numpy as np 

In [3]:
#Q1-Write a NumPy program to swap rows and columns of a given array in reverse order.
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print("The initial array = \n",arr1)
arr1 = np.transpose(arr1)
arr1 = np.flip(arr1 , axis = 0) 
arr1 = np.flip(arr1 , axis = 1)
print ("The solution array is = \n" ,arr1)


The initial array = 
 [[1 2 3]
 [4 5 6]]
The solution array is = 
 [[6 3]
 [5 2]
 [4 1]]


In [28]:
'''Q2(a)- Write a NumPy program to find the most frequent value in an array.
array:
[6 9 5 1 4 6 7 8 9 8 7 1 7 5 1 0 1 5 5 0 8 9 0 7 0 7 6 5 1 1 9 5 3 8 7 9 
6 3 4 5 9 7 2 7 0 2 2 6]
-b)sort the frequent values in descending order'''

arr2 = list("6 9 5 1 4 6 7 8 9 8 7 1 7 5 1 0 1 5 5 0 8 9 0 7 0 7 6 5 1 1 9 5 3 8 7 9 6 3 4 5 9 7 2 7 0 2 2 6")
n = arr2.count(" ")
i = 0
for i in range(n):
    arr2.remove(" ")
arr2 = [eval(j) for j in arr2 ]
arr2 = np.array(arr2)
print("The initial array is = ")
print(arr2)
unique, frequency = np.unique(arr2 ,return_counts = True)
dic1 = {}
i = 0
for i in range(len(unique)):
    dic1["%d"%unique[i]] = frequency[i]
print(dic1)
dic1 = dict(sorted(dic1.items() , reverse = True , key = lambda x:x[1]))
print("The frequent value in reverse order is \n",dic1)



    





The initial array is = 
[6 9 5 1 4 6 7 8 9 8 7 1 7 5 1 0 1 5 5 0 8 9 0 7 0 7 6 5 1 1 9 5 3 8 7 9 6
 3 4 5 9 7 2 7 0 2 2 6]
{'0': 5, '1': 6, '2': 3, '3': 2, '4': 2, '5': 7, '6': 5, '7': 8, '8': 4, '9': 6}
The frequent value in reverse order is 
 {'7': 8, '5': 7, '1': 6, '9': 6, '0': 5, '6': 5, '8': 4, '2': 3, '3': 2, '4': 2}


In [138]:
'''Q3- Write a Pandas Program to create a dataframe such that the column labels are Name, Rollnumber, Subject1, Subject2 and Total
i)	Using Pandas function itself calculate the statistical summary(mean, median, mode, Quartiles, etc) of all the numerical columns.
ii)	Sort the entire dataframe based on the alphabetical order 
iii)	Change the dataset such that there are missing values and NAN values in the dataset and handle them appropriately.'''
data1 = [['Vihaan',9,90,90],['Abhijeet',3,85,91],['Tarun',5,95,78],['Kalash',1,78,87]]
for i in range(len(data1)):
    data1[i].append(data1[i][2]+data1[i][3])
df1 = pd.DataFrame(data1 , columns=['Name','Rollnumber','Subject1','Subject2','total'])
print(df1)
print(df1.describe())
print("Data Frame sorted by alphabetical order:")
df1 = df1.sort_values(by = ['Name'])
print(df1)
data2 = [['Vihaan',9,np.nan,90,180],['Abhijeet',np.nan,85,91,176],['Tarun',5,95,np.nan,173],['Kalash',1,78,87,np.nan]]
df2 = pd.DataFrame(data2 , columns=['Name','Rollnumber','Subject1','Subject2','total'])
print("\n Now Adding a few missing values \n",df2)
ind = 0
for ind in range(len(df2)):
    if np.isnan(df2.at[ind,"Subject1"]) == True:
        df2.at[ind,'Subject1'] = df2.at[ind,"total"] - df2.at[ind,"Subject2"]
    if np.isnan(df2.at[ind,"Subject2"]) == True:
        df2["Subject2"][ind] = df2.at[ind,"total"] - df2.at[ind,"Subject1"]
    if np.isnan(df2.at[ind,"total"]) == True:
        df2["total"][ind] = df2.at[ind,"Subject1"] + df2.at[ind,"Subject2"]    
df2.dropna(inplace = True)
print("\n The corrected data frame is : \n",df2)


       Name  Rollnumber  Subject1  Subject2  total
0    Vihaan           9        90        90    180
1  Abhijeet           3        85        91    176
2     Tarun           5        95        78    173
3    Kalash           1        78        87    165
       Rollnumber  Subject1  Subject2       total
count     4.00000   4.00000   4.00000    4.000000
mean      4.50000  87.00000  86.50000  173.500000
std       3.41565   7.25718   5.91608    6.350853
min       1.00000  78.00000  78.00000  165.000000
25%       2.50000  83.25000  84.75000  171.000000
50%       4.00000  87.50000  88.50000  174.500000
75%       6.00000  91.25000  90.25000  177.000000
max       9.00000  95.00000  91.00000  180.000000
Data Frame sorted by alphabetical order:
       Name  Rollnumber  Subject1  Subject2  total
1  Abhijeet           3        85        91    176
3    Kalash           1        78        87    165
2     Tarun           5        95        78    173
0    Vihaan           9        90        90    180

C:\Users\vihaa\AppData\Local\Temp\ipykernel_27840\526618440.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Subject2"][ind] = df2.at[ind,"total"] - df2.at[ind,"Subject1"]
C:\Users\vihaa\AppData\Local\Temp\ipykernel_27840\526618440.py:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["total"][ind] = df2.at[ind,"Subject1"] + df2.at[ind,"Subject2"]
